FROM node:22.8.0-slim

RUN apt update && \
  apt install -y curl && \
  npm install -g nodemon

WORKDIR /home/node/app

RUN chown -R node:node /home/node

# debian  
# RUN useradd -m -u 1000 admin - criar um usuario
# RUN usermod -u 1000 admin - muda o id de um usuário

# alpine  
# RUN adduser -D -u 1000 admin
# RUN sed -i 's/1000/1001/g' /etc/passwd
  
USER node

COPY package.json ./
RUN npm install

